### PR TITLE
global: Adds env name

### PR DESCRIPTION
**Pull request by jrcastro2**

### CODE REVIEW

**Review by FlorianCassayre — APPROVED** [review]
Missing a newline at the end, but it seems to work regardless.

**Comment by jrcastro2** [comment]
> Missing a newline at the end, but it seems to work regardless.

Even if we can not see it it's there :/ . (I added it)

**Comment by FlorianCassayre** [comment]
My bad then :+1:

**Review by ntarocco — APPROVED** [review]
Thanks!!! 💯

**Pull request merged**
